### ISSUE TITLE
POST pulls/reviews: 502 Server Error

### ISSUE THREAD

**Issue by mgrachev** [reviewdog/reviewdog#355]
Hi there!

I use rubocop with reviewdog and If I have more than 30 comments then I got the error:
```
reviewdog: POST https://api.github.com/repos/<repo>/pulls/49/reviews: 502 Server Error []
```

Although 30 comments have been created and I see the message:
> Remaining comments which cannot be posted as a review comment to avoid GitHub Rate Limit

**Comment by sobolevn** [comment]
The same here.

I have tried this on two different repos.
- https://github.com/wemake-services/wemake-python-styleguide/commit/3eeb3a409583da7a1218eb75b2be20f0ac2ad62f/checks?check_suite_id=336450757
- https://github.com/sobolevn/python-pure-evil/commit/595f0e5fd9c4bc9b17dfbec35535cd3f2c9e4059/checks?check_suite_id=336447207

Can we fix rate-limits with `GITHUB_TOKEN`?

**Comment by sobolevn** [comment]
My PRs:
- https://github.com/wemake-services/wemake-python-styleguide/pull/1045
- https://github.com/sobolevn/python-pure-evil/pull/1

**Comment by haya14busa** [comment]
Sry, I didn't include the fix to the latest release. It should work in master branch.
I'll release a new version.

**Comment by sobolevn** [comment]
@haya14busa thanks a lot! 

P.S. What an awesome tool you, guys, made! Thanks a lot!

**Comment by mgrachev** [comment]
@haya14busa Thanks!

P.S. Hi @sobolevn! Nice to see you here 😃

**Comment by haya14busa** [comment]
I released new version. https://github.com/reviewdog/reviewdog/releases/tag/v0.9.14
Can you re-try with the latest version?

Thanks!

**Comment by sobolevn** [comment]
@haya14busa @mgrachev it is still failing. But, it now has different behaviour!

It actually comments stuff, but fails with `502` anyway.

Here's the PR link with comments: https://github.com/wemake-services/wemake-python-styleguide/pull/1049
Reviewdog version: https://github.com/wemake-services/wemake-python-styleguide/commit/9e485a39a18c2132d362f01f090dd8bac00299b0/checks?check_suite_id=338146118#step:2:217 `0.9.14`
Error message: https://github.com/wemake-services/wemake-python-styleguide/commit/9e485a39a18c2132d362f01f090dd8bac00299b0/checks?check_suite_id=338146118#step:4:99 `reviewdog: POST https://api.github.com/repos/wemake-services/wemake-python-styleguide/pulls/1049/reviews: 502 Server Error []`
